//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcShopDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Felhasznalo
    {
        public decimal ID { get; set; }
        public string NEV { get; set; }
        public string BEOSZTAS { get; set; }
        public string FelhasznaloNev { get; set; }
        public string Jelszo { get; set; }
    }
}
