//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcShopDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PcAlkatreszek
    {
        public decimal ID { get; set; }
        public string TIPUS { get; set; }
        public string ALAPLAP { get; set; }
        public Nullable<decimal> VIDEOKARTYA { get; set; }
        public Nullable<decimal> PROCESSZOR { get; set; }
        public Nullable<decimal> HDD { get; set; }
        public Nullable<decimal> SSD { get; set; }
        public Nullable<decimal> MEMORIA { get; set; }
    
        public virtual PC PC { get; set; }
    }
}
