//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcShopDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PcRendelesre
    {
        public decimal ID { get; set; }
        public decimal RENDID { get; set; }
        public string TIPUS { get; set; }
        public Nullable<decimal> STATUSZ { get; set; }
    }
}
