//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcShopDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzenetek
    {
        public decimal ID { get; set; }
        public string FELADO { get; set; }
        public string CIMZETT { get; set; }
        public Nullable<System.DateTime> KULDESDATUM { get; set; }
        public string KOZLEMENY { get; set; }
    }
}
